export const AvailableConfigs = {
    PORT: "PORT",
    MONGODB_CONNECTION_STRING: "MONGODB_CONNECTION_STRING",
    SECRET: "SECRET",
    SENDGRID_API_KEY: "SENDGRID_API_KEY",
    SENDGRID_SENDER_EMAIL: "SENDGRID_SENDER_EMAIL",
}